### ISSUE TITLE
Errors in apache logs

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_auth_registration#6] opened 2016-09-16 19:30 UTC
I see a lot of these errors in the Apache logs:

```
[Wed Sep 14 22:13:29.504047 2016] [:error] [pid 24234] [client 129.137.215.242:47377] PHP Notice:  Undefined index: logindisabled in /var/www/ood/register/ldap.php on line 177, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:29.581208 2016] [:error] [pid 24234] [client 129.137.215.242:47377] PHP Notice:  Undefined index: OIDC_CLAIM_eppn in /var/www/ood/register/index.php on line 87, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:32.154119 2016] [:error] [pid 72607] [client 129.137.215.242:24156] PHP Notice:  Undefined index: logindisabled in /var/www/ood/register/ldap.php on line 177, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:32.637211 2016] [:error] [pid 72607] [client 129.137.215.242:24156] PHP Notice:  Undefined index: OIDC_CLAIM_eppn in /var/www/ood/register/index.php on line 87, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:42.172018 2016] [:error] [pid 55136] [client 129.137.215.242:47260] PHP Notice:  Undefined index: logindisabled in /var/www/ood/register/ldap.php on line 177, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:42.248271 2016] [:error] [pid 55136] [client 129.137.215.242:47260] PHP Notice:  Undefined index: OIDC_CLAIM_eppn in /var/www/ood/register/index.php on line 87, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
[Wed Sep 14 22:13:46.944139 2016] [:error] [pid 59742] [client 129.137.215.242:16280] PHP Notice:  Undefined index: logindisabled in /var/www/ood/register/ldap.php on line 177, referer: https://ondemand.osc.edu/register/?redir=%2fpun%2fsys%2fdashboard
```

Not sure if they are bugs or just warnings.

**Comment by ericfranz** [comment] 2016-11-18 19:33
duplicate of #7

**Closed as completed by ericfranz** 2016-11-18 19:33 UTC
Labels: bug, duplicate
